new_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path("my_app/", include("my_app.urls")),
    path('', include('users.urls')),
    path('api/', include('api.urls')),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='reset_password.html'),
         name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='reset_password_sent.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='reset.html'),
         name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='reset_password_complete.html'),
         name='password_reset_complete')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# ეს გვჭირდება იმისთვის რომ პროექტის გვერდზე რო გადავალთ სტატიკური ფაილები გვიჩვენოს
# MEDIA_ROOT = os.path.join(BASE_DIR, 'static/images')
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# ეს ქვედაც  იგივეა მარა,
# DEBUG = False
# ALLOWED_HOSTS = ['localhost', '127.0.0.1']
# რომ შევცვალეთ აღარ გვაჩვენბდა სურათებს და მაგისთვისააა
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("my_app/", include("my_app.urls")),
    path('', include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# ეს გვჭირდება იმისთვის რომ პროექტის გვერდზე რო გადავალთ სტატიკური ფაილები გვიჩვენოს
# MEDIA_ROOT = os.path.join(BASE_DIR, 'static/images')
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# ეს ქვედაც  იგივეა მარა,
# DEBUG = False
ALLOWED_HOSTS = ['*']
# რომ შევცვალეთ აღარ გვაჩვენბდა სურათებს და მაგისთვისააა
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

users/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerUser, name='register'),
    path('account/', views.userAccount, name='account'),
    path('', views.profiles, name='profiles'),
    path('profile/<str:pk>/', views.userProfile, name='profile'),
    path('edit-account/', views.edit_account, name='edit-account'),
    path('create-skill/', views.create_skill, name='create-skill'),
    path('update-skill/<str:pk>/', views.update_skill, name='update-skill'),
    path('delete-skill/<str:pk>/', views.delete_skill, name='delete-skill'),
    path('inbox', views.inbox, name='inbox'),
    path('message/<str:pk>/', views.viewMessage, name='message'),
    path('send-message/<str:pk>/', views.sendMessage, name='send-message')
]

my_app/models.py
from django.db import models
import uuid
from users.models import Profile

# Create your models here.


class Projectebi(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    demo_link = models.CharField(max_length=200, null=True, blank=True)
    source_link = models.CharField(max_length=200, null=True, blank=True)

    #ესენი ჩვეულებრივი ფილდებია
    # null=True, არის რომ მონაცემთა ბაზა დათანხმდეს ცარიელ ფილდს და blank=True არის რო ჯანგო დათანხმდეს
    featured_image = models.ImageField(null=True, blank=True, default='default_img.png')
    # python -m pip install pillow ეს ბრძანება უნდა გავუშვათ ტერმინალში აი ამან default='default_img.png'  რო იმუშაოს.
    # მარა მარტო ეგ არ ყოფნის, პითონის  ბიბლიოთეკაა საჭირო. ინსტალაცია: python -m pip install whitenoise და
    # settings.py-ში, MIDDLEWARE -ში ამ ჩანაწერის დამატება "whitenoise.middleware.WhiteNoiseMiddleware"
    # ამ დროს ყველაფრის ჩვენება ხდება staticfiles-დან და არა static-დან იმიტომ რომ DEBUG = False,
    # რაც იმას ნიშნავს რომ თუ რამე ცვლილებას
    # შევიტანთ სადმე სტატიკურ ფაილებში (css, html, ფოტო და ა.შ) ბრაუზერში ვერ დავინახავთ, ანუ არ შეიცვლება.
    # საჭიროა გავუშვათ ბრძანება python manage.py collectstatic ან DEBUG = True-ზე დავაყენოთ

    created = models.DateTimeField(auto_now_add=True)

    # ამ სამ შორის ჯერ არ ვიცი განსხვავება მარა ეს მესამე საათის და თარიღის ჩასაწერს აგდებს და უნდა ჩავწეროთ ან ავირჩიოთ

    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    # UUIDField არის 16 ნიშნა აიდი ციფრებითა და ასოებით.
    # default=uuid.uuid4 ეს არის დაშიფვრის მეთოდი
    # unique=True ამას ვწერთ თუ გვინდა რომ აიდი უნიკალური იყოს
    # primary_key=True ამას ვწერთ თუ გვინდა რომ აიდი primary key-დ გამოვიყენოთ.
    # editable=False დაედითება აკრძალულია

    tags = models.ManyToManyField('Tag', blank=True)
    #ამ ხაზით ვუკავშირებთ ერთმანეთს ამ და ქვემოთ დაწერილ ცვრილს (Tag). 'Tag' იმიტოა ბრჭყალებშ რომ მაგის კლასის ქვემოთაა,
    #ამ კლასის ზემოთ რო წერებულიყო ბრჭყალების გარეშეც წავა.
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    # ზედა დათვლის მიცემულ ხმებს ქვედა პროცენტებს


    def __str__(self):
        return self.title   # აქ რასაც დავწერთ ამას დაარქმევს ადმინის ექაუნთში ჩვენ პროექტებს



    """
    class Meta:
        ordering = ['created']
    
        # ეს დაალაგებს პროექტებს შექმნის თარიღის მიხედვით. თუ დავწერდით  '-created' მაშინ შებრუნებულად მარა ისევ თარიღით
        # 'created'-ის მაგივრად შევიძლია ასევე სხვა პარამეტრის არჩვეაც...
    """


    class Meta:
        ordering = ['-vote_ratio', '-vote_total', 'title']
        # ეს დაალაგებს პროექტებს -vote_ratio-ს მიხედვით. თუ -vote_ratio ტოლები აქ ორს მაშინ  'vote_total'-ის
        # მიხედვით და თუ ეგეც ტოლებია მაშინ 'title'-ის მიხედვით. ზედა მეტა აღარ გვჭირდება.
        # ანუ das heißt შეგვიძლია პროექტები ან სხვა რამეებიც ყოველტვის დავალაგოთ მოდელში არსებული
        # რომელიმე ფილდის ან ფილდების  მიხედვით

    @property
    def reviewers(self):
        queryset = self.review_set.all().values_list('owner__id', flat=True)
        return queryset
        # გადმოიტანს ყველა რივიუს "review_set.all()" ვალუების
        # (value არის ტექსტის ფილდი რივიუს მოდელებში) "values_list"
        # ოუნერებს (ანუ ვინც დაწერა)  ლისტის სახით "owner__id".
        # ეს flat=True რას აკეთებს კარგად ვერ გავიგე

    @property    # ამ @property-ს ტუ დავაკომენტარებს get_vote_count ყვითლად არარ იქნება. საინტერესოა....
    def get_vote_count(self):
        reviews = self.review_set.all()
        upVotes = reviews.filter(value='up').count()
        totalVotes = reviews.count()

        ratio = (upVotes / totalVotes) * 100
        self.vote_total = totalVotes
        self.vote_ratio = ratio
        self.save()
    # ეს ფუქცია თვლის პროექტების რივიუებს და პოზიტიური რივიუების პროცენტობას. მე მგონი ყველაფერი გასაგებია

class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up vote'),
        ('down', 'Down vote'),
    )
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    # ამ ზედა ხაზით ვაბამთ პროფილს ForeignKey-ით კომენტარის ავტორზე.
    # ანუ ავტომატურად კომენტარის ავტორი იქნება ის ვისი ფროფილიდანაც დაიწერა.
    projecti = models.ForeignKey(Projectebi, on_delete=models.CASCADE)
    #  on_delete=models.SET_NULL ან CASCADE . განსხვავება არის რომ მშობელი ცხრილის წაშლისას პირველ შემთხვევაში
    # შვილი ცხრილები დარჩებიან მეორე შეთხვევაში კი ესეც ავტომატურად წიშლება.
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=20, choices=VOTE_TYPE)
    # choices=VOTE_TYPE  ამით შექმნება ამოსარჩევი პასუხები ანუ ჩამონათვალი უნდა ავირჩიოთ

    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    class Meta:
        unique_together = [['owner', 'projecti']]
        # ამ მეტა კლასით, სადა unique_together უდრის ცხრილს ცხრილში 'owner' და  'projecti'
        # რომლებიც ამავე მოდელში გვაქ ვაკეთებთ (ვეუბნებით ჯანგოს) ასეთ რამეს რომ ეს ორი 'owner' და  'projecti'
        # ერთად უნიკალურები არიან და 'owner'-ს არ შეუძლია საკუტარ თავს კომენტარი დაუწეროს.


    def __str__(self):
        return self.value




class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    def __str__(self):
        return self.name
    # ამ თაგებით შეგვიძლია დავთაგოთ პროექტები და პროქტს რო გავხსნიტ გამოჩნდებიან რითიც დავთაგავთ

users/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User

from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver



# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    username = models.CharField(max_length=100, blank=True, null=True, default='park')
    location = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField(max_length=100, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    short_intro = models.TextField(blank=True, null=True)
    profile_pic = models.ImageField(blank=True, null=True, upload_to='profile_pics', default='profile_pics/mehdi.png')
    # ეს ორი რაღაცა (upload_to='profile_pics', default='profile_pics/mehdi.png') აკეთებს შემდეგ რამეს:
    # პირველი ეუბნება ჯანგოს თუ სად უნდა შეინახოს ატვირთული ფოტოები.
    # მეორე ეუბნება ჯანგოს თუ ფოტო არ ატვირტესო მიეცი ავტომატურად რამე სტანდარტული ფოტოო. (ვითომ კაცი)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    social_media = models.CharField(max_length=100, blank=True, null=True)
    wiki = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return str(self.username)



class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.name)



class Message(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    recipient = models.ForeignKey(Profile, on_delete=models.SET_NULL,
                                  null=True, blank=True, related_name='messages')
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    file = models.FileField(blank=True, null=True, upload_to='message_files')
    def __str__(self):
        return self.subject

    class Meta:
        ordering = ['is_read', '-created']

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Skill, Message




# UserCreationForm  რომ ჩავსვით როგორც პარამეტრი CustomUserCreationForm-ში ეს იმას ნიშნავს რომ
# CustomUserCreationForm გახდა ჩვეულებრივად ის რაც UserCreationForm იყო თავის ინფუთებით.
# views.py-ში რომ გვაქ ფუნქცია registerUser,  მანდ გვჭირდებოდა ეს UserCreationForm და ახლა შეგვიძლია
# იქ ამის მაგივრად უბრალოდ ეს ჩვენი ახლად შექმნილი კლასი class CustomUserCreationForm დავაიმპორტოთ
# და იგივე საქმეს გაგვიკეთებს იმიტო რომ იგივე ფუნქციონალიტეტი აქვს.
# ეს 'password1' და 'password2' გვჭირდება იმისთვის რო შედარდნენ პაროლები.
# მთლიანად ეს ფუქნცია იმისთვის გვჭირდება რომ UserCreationForm-ს ქონდა მარტო სამი ფილდი:
# Username, password და confirm password. ჩვენ კიდე ამით  ვამატებთ კიდევ ორს first_name-ს და  'email-ს
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2']
        labels = {
            'first_name': 'Name'
        }
        # ეს labels დიქშიონარი რეგისტრაციის გვერდზე First Names-ის მაგივრად ლეიბლს დაარქმევს Name.

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})
    # ეს ბოლო ფუქცია აკეთებს ასეთ რამეს რო ამ ფორმის ფილდები ამის გარეშე იყვნენ მოკლე და ვიწრო,
    # ამით კიდე კარგად გამოიყურებიან და ავსებენ სივრცეს



class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = [
            'name',
            'username',
            'email',
            'location',
            'short_intro',
            'bio',
            'social_media',
            'wiki',
            'profile_pic']
        # ეს ლისტი იმიტო არის პროფილის მოდელის ლისტიდან ამოწერილი ფილდები რომლებიც გვინდა რომ იუზერმა
        # პროფილის რედაქტირებისას შეავსოს. შეგვეძლო გვქონდა '__all__' რაც ყველა ფილსდ გამოიტანადა.
        # ისეთებსაც რომლებიც საჭირო არაა.
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})



class SkillForm(ModelForm):
    class Meta:
        model = Skill
        fields = '__all__'
        exclude = ['owner']

    def __init__(self, *args, **kwargs):
        super(SkillForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})



class UpdateSkillForm(ModelForm):
    class Meta:
        model = Skill
        fields = '__all__'
        exclude = ['owner']

    def __init__(self, *args, **kwargs):
        super(UpdateSkillForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})



class WriteMessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['name', 'email', 'subject', 'body', 'file']

    def __init__(self, *args, **kwargs):
        super(WriteMessageForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

users/templates/users/account.html
{% extends 'base.html' %}
{% block tani %}


  <!-- Main Section -->
  <main class="settingsPage profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'edit-account' %}"><i class="im im-edit"></i> Edit</a>
              <img class="avatar avatar--xl dev__avatar" src="{{ profile.profile_pic.url }}" />
              <h2 class="dev__name">{{ profile.name }}</h2>
              <p class="dev__title">{{ profile.short_intro }}</p>
              <p class="dev__location">Location: {{ profile.location }}</p>
              <ul class="dev__social">
                {% if profile.wiki %}
                <li>
                  <a title="Github" href="{{ profile.wiki }}" target="_blank"><i class="im im-github">wiki</i></a>
                </li>
                {% endif %}
                {% if profile.social_media %}
                <li>
                  <a title="twitter" href="{{ profile.social_media }}" target="_blank"><i class="im im-stackoverflow">social</i></a>
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{ profile.bio }}
            </p>
          </div>
          <div class="settings">
            <h3 class="settings__title">Skills</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-skill' %}?next=/account"><i class="im im-plus"></i> Add Skill </a>
          </div>

          <table class="settings__table">
            {% for skill in skills %}
            <tr>
              <td class="settings__tableInfo">
                <h4>{{ skill.name }}</h4>
                <p>
                 {{ skill.description|slice:"200" }}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-skill' skill.id %}"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-skill' skill.id %}?next=/account"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            {% endfor %}

          </table>

          <div class="settings">
            <h3 class="settings__title">Projects</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-project' %}?next=/account"><i class="im im-plus"></i> Add Project</a>
          </div>

          <table class="settings__table">
            {% for project in projects %}
            <tr>
              <td class="settings__thumbnail">
                <a href="{% url 'projects' project.id %}"><img src="{{ project.featured_image.url }}" alt="Project Thumbnail" /></a>
              </td>
              <td class="settings__tableInfo">
                <a href="{% url 'projects' project.id %}">{{ project.title }}</a>
                <p>
                 {{ project.description|slice:"150" }}

                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-project' project.id %}"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-project' project.id %}?next=/account"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            {% endfor %}

          </table>
        </div>
      </div>
    </div>
  </main>
{%  endblock %}

users/templates/users/inbox.html
{% extends 'base.html' %}
{% block tani %}
  <main class="inbox my-xl">
    <div class="content-box">
      <h3 class="inbox__title">New Messages(<span>{{ unreadCount }}</span>)</h3>
      <ul class="messages">
        {% for message in messageRequests %}
        {% if message.is_read == False %}
        <li class="message message--unread">
        {% else %}
        <li class="message">
        {% endif %}
          <a href="{% url 'message' message.id %}">
            <span class="message__author">{{ message.sender.name }}</span>
            <span class="message__subject">{{ message.subject }}</span>
            <span class="message__date">{{ message.created }}</span>
          </a>
        </li>
        {% endfor %}

      </ul>
    </div>
  </main>
{% endblock tani %}

users/templates/users/message.html
{% include 'base.html' %}
{% block tani %}
  <!-- Main Section -->
  <main class="messagePage my-xl">
    <div class="content-box">
      <div class="message">
        <a class="backButton" href="{% url 'inbox' %}"> <i class="im im-angle-left"> Back</i></a>
        <h2 class="message__subject">{{ message.subject }}</h2>
          <a href="{% url 'profile' message.sender.id %}" class="message__author">
              {{ message.sender }} </a>
          <p class="message__date">{{ message.created }}</p>
          <div class="message__body">
            {{ message.body | linebreaksbr}}
      </div>
    </div>

  </main>
{% endblock tani %}

users/templates/users/profiles.html
{% extends 'base.html' %}

{% block tani %}







  <main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form id="searchForm" class="form" action="{% url 'profiles' %}" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="search_query" value="{{ search_query }}"
                placeholder="Search by developer name" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>


    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
            <div class="grid grid--three" >

                  {% for profile in profiles %}
                  <div class="column card" >
                    <div class="dev">
                      <a href="{% url 'profile' profile.id %}" class="card__body">
                        <div class="dev__profile">
                          <img class="avatar avatar--md" src="{{ profile.profile_pic.url }}" alt="image" />
                          <div class="dev__meta">
                            <h3>{{ profile.name }}</h3>
                            <h5>{{ profile.short_intro}}</h5>
                          </div>
                        </div>
                        <p class="dev__info">
                            {{ profile.bio|slice:"200" }}
                        </p>

                        <div class="dev__skills">
                          {% for skill in profile.skill_set.all|slice:"5" %}
                          <span class="tag tag--pill tag--main">
                            <small>{{ skill }}</small>
                          </span>
                          {% endfor %}
                        </div>

                      </a>
                    </div>
                  </div>
                  {% endfor %}

            </div>



      </div>
    </section>
    {% include 'pagination.html'  with queryset=profiles custom_range=custom_range %}


  </main>


{% endblock %}

users/templates/users/user_profile.html
{% extends 'base.html' %}

{% block tani %}







  <main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{ profile.profile_pic.url }}" />
              <h2 class="dev__name">{{ profile.name }}</h2>

              <p class="dev__title">{{ profile.short_intro }}</p>

              <p class="dev__location">location: {{ profile.location }}</p>
              <ul class="dev__social">
                {% if profile.wiki %}
                <li>
                  <a title="Github" href="{{ profile.wiki }}" target="_blank"><i class="im im-github">wiki</i></a>
                </li>
                {% endif %}
                {% if profile.social_media %}
                <li>
                  <a title="twitter" href="{{ profile.social_media }}" target="_blank"><i class="im im-stackoverflow">social</i></a>
                </li>
                {% endif %}

              </ul>
              {% if profile.id != user.profile.id %}
              <a href="{% url 'send-message' profile.id  %}" class="btn btn--sub btn--lg">Send Message </a>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            {% for x in beso %}
            <h3 class="devInfo__title">About Me {{ x }}</h3>
            {% endfor %}

            <h3 class="devInfo__about">{{ profile.bio }}<br /></h3>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">
            {{ skill }}

              {% for skill in topSkills %}
                  <div class="devSkill">
                    <h4 class="devSkill__title">{{ skill.name }}</h4>
                    <p class="devSkill__info">
                      {{ skill.description }}
                    </p>
                  </div>
              {% endfor %}



              <div class="devInfo__otherSkills">
                {% for skill in otherSkills %}
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{ skill.name }}</small>
                </span>
                {% endfor %}
              </div>

            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">


            {% for project in profile.projectebi_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="{% url 'projects' project.id %}" class="project">
                    <img class="project__thumbnail" src="{{ project.featured_image.url }}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{ project.title }}</h3>
                      <p><a class="project__author" href="{% url 'profile' project.owner.id %}">{{ project.owner}}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{ project.vote_ratio}}</span> Postitive
                        Feedback ({{ project.vote_total }} Vote{{ project.vote_total|pluralize:'s' }})
                      </p>
                      <div class="project__tags">
                      {% for tag in project.tags.all %}
                        <span class="tag tag--pill tag--main">
                          <small>{{ tag }}</small>
                        </span>
                      {% endfor %}
                      </div>



                    </div>
                  </a>
                </div>
              </div>
            {% endfor %}


            </div>
          </div>
        </div>
      </div>
    </div>
  </main>





{% endblock %}